# Generated by Django 4.1.7 on 2023-03-27 06:29

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cinema',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('gender_rate', models.IntegerField(max_length=4)),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=20)),
                ('sur_name', models.CharField(max_length=20)),
                ('second_name', models.CharField(max_length=20)),
                ('age', models.IntegerField(max_length=4)),
                ('gender', models.CharField(max_length=20)),
            ],
        ),
    ]
